apiVersion: apps/v1
kind: Deployment
metadata:
   name: chat-deployment
   labels:
     app: {{ .Values.Deployments.app_name }}
spec:
   replicas: {{ .Values.Deployments.app_replicas }}
   selector:
     matchLabels:
       app: {{ .Values.Deployments.app_name }}
   template:
     metadata:
       labels:
         app: {{ .Values.Deployments.app_name }}
     spec:
       affinity:
#         nodeAffinity:
#           requiredDuringSchedulingIgnoredDuringExecution:
#             nodeSelectorTerms:
#             - matchExpressions:
#               - key: name
#                 operator: In
#                 values:
#                 - kworker1
#                 - kworker2
         podAntiAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
           - labelSelector:
               matchExpressions:
               - key: app
                 operator: In
                 values:
                 - {{ .Values.Deployments.app_name }}
             topologyKey: "kubernetes.io/hostname"
       containers:
       - name: {{ .Values.Deployments.app_name }}
         image: {{ .Values.Deployments.app_url }}
         imagePullPolicy: Always
         envFrom:
         - configMapRef:
             name: {{ .Values.Deployments.app_env }}
         ports:
         - containerPort: {{ .Values.Deployments.app_port }}
         resources: 
           limits: 
             cpu: 500m
           requests:
             cpu: 250m
