apiVersion: apps/v1
kind: Deployment
metadata:
   name: chat-deployment
   labels:
     app: chatapplication
spec:
   #replicas: 2
   selector:
     matchLabels:
       app: chatapplication
   template:
     metadata:
       labels:
         app: chatapplication
     spec:
       affinity:
         nodeAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
             - matchExpressions:
               - key: name
                 operator: In
                 values:
                 - worker1
                 - worker2
         podAntiAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
           - labelSelector:
               matchExpressions:
               - key: app
                 operator: In
                 values:
                 - chatapplication
             topologyKey: "kubernetes.io/hostname"
       containers:
       - name: chatapplication
         image: 760496128264.dkr.ecr.ap-south-1.amazonaws.com/chatapp:chatapp13_chat
         envFrom:
         - configMapRef:
             name: postgres-config
         ports:
         - containerPort: 8000 
         resources: 
           limits: 
             cpu: 250m
