apiVersion: v1
kind: Service
metadata:
  name: database1
  labels:
    app: {{ .Values.Service.db_name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.Service.db_svc }}
    targetPort: {{ .Values.Service.db_svc }}
  selector:
    app: {{ .Values.Service.db_name }}


